[package]
name = "geek-mail"
version = "0.1.0"
authors = ["jboyett"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { version = "0.5", features = ["web"] }

# Debug
dioxus-logger = "0.5.1"
imp = "0.1.0"
